# Generated by Django 3.2 on 2024-02-22 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('direccion', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, upload_to='sitio')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('ingeniero_asig', models.TextField(null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='apiweb.sitio')),
            ],
        ),
    ]
